<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldInvoice.Application\GoldInvoice.Application.csproj" />
    <ProjectReference Include="..\GoldInvoice.Contracts\GoldInvoice.Contracts.csproj" />
    <ProjectReference Include="..\GoldInvoice.Infrastructure\GoldInvoice.Infrastructure.csproj" />
  </ItemGroup>

</Project>
