import type { DashboardSnapshot } from "./dashboard.types";

export const dashboardMock: DashboardSnapshot = {
  profile: {
    displayName: "علی بقائی",
    role: "مدیر زرگری",
    initials: "ع‌ب",
  },
  quickOperations: [
    {
      id: "daily-operations",
      title: "عملیات روزانه",
      description: "باز کردن صندوق، مرور فعالیت روز و بستن دفاتر.",
      meta: "۱۸ کار امروز",
    },
    {
      id: "trust-funds",
      title: "وجوه امانی",
      description: "سپرده‌های امانی مشتریان، تخصیص‌ها و آزادسازی‌ها.",
      meta: "۲۷۴٬۶۰۰ دلار امانت",
    },
    {
      id: "installments",
      title: "اقساط",
      description: "فروش اقساطی، جدول پرداخت و وضعیت وصول.",
      meta: "۴۲ طرح فعال",
    },
    {
      id: "settlement",
      title: "تسویه فاکتور",
      description: "دریافت وجه، تسویه مانده‌ها و مرور تاریخچه پرداخت.",
      meta: "۹ فاکتور در انتظار",
    },
    {
      id: "bank-interest",
      title: "سود بانکی",
      description: "سود دریافتی سپرده‌ها و سود پرداختی تسهیلات.",
      meta: "+۱۲٬۴۸۰ دلار از ابتدای ماه",
    },
    {
      id: "bank-loans",
      title: "وام‌های بانکی",
      description: "تسهیلات، مانده بدهی، اقساط ماهانه و سود.",
      meta: "۳ تسهیلات",
    },
  ],
  metrics: [
    {
      id: "today-sales",
      label: "فروش امروز",
      value: "$۱۸۴,۲۵۰",
      hint: "نسبت به دیروز",
      trend: "۱۲.۴٪",
      direction: "up",
    },
    {
      id: "today-profit",
      label: "سود امروز",
      value: "$۴۶,۸۷۰",
      hint: "حاشیه سود ۲۵٫۴٪",
      trend: "۸.۱٪",
      direction: "up",
    },
    {
      id: "monthly-revenue",
      label: "درآمد ماهانه",
      value: "$۳,۴۲۸,۹۰۰",
      hint: "مرداد ۱۴۰۵",
      trend: "۵.۷٪",
      direction: "up",
    },
    {
      id: "pending-orders",
      label: "سفارش‌های در انتظار",
      value: "۲۴",
      hint: "۶ سفارش منتظر نگین",
      trend: "۳.۲٪",
      direction: "down",
    },
    {
      id: "issued-invoices",
      label: "فاکتورهای صادرشده",
      value: "۱۳۸",
      hint: "این ماه",
      trend: "۴.۴٪",
      direction: "up",
    },
    {
      id: "inventory-value",
      label: "ارزش انبار",
      value: "$۱۲,۸۴۰,۵۰۰",
      hint: "۱٬۲۰۴ قطعه",
      trend: "۲.۱٪",
      direction: "up",
    },
    {
      id: "receivables",
      label: "مطالبات وصول‌نشده",
      value: "$۴۸۶,۳۰۰",
      hint: "۳۱ حساب",
      trend: "۶.۸٪",
      direction: "down",
    },
    {
      id: "customer-deposits",
      label: "سپرده مشتریان",
      value: "$۲۷۴,۶۰۰",
      hint: "وجوه امانی",
      trend: "۱.۹٪",
      direction: "up",
    },
  ],
  market: {
    updatedAt: "لحظاتی پیش",
    goldPrices: [
      {
        label: "طلای ۱۸ عیار",
        value: "$۲,۴۵۲.۱۰",
        unit: "/اونس",
        trend: "۰.۷۲٪",
        direction: "up",
      },
      {
        label: "طلای ۲۴ عیار",
        value: "$۲,۳۱۶.۴۰",
        unit: "/اونس",
        trend: "۰.۶۴٪",
        direction: "up",
      },
    ],
    trading: [
      { label: "خرید", value: "$۲,۴۳۸.۰۰" },
      { label: "فروش", value: "$۲,۴۶۶.۵۰" },
    ],
    currencies: [
      {
        label: "دلار ← ریال",
        value: "۱,۰۴۲,۰۰۰",
        trend: "۰.۳۱٪",
        direction: "up",
      },
      {
        label: "ریال ← دلار",
        value: "۰.۰۰۰۰۰۰۹۶",
        trend: "۰.۳۱٪",
        direction: "down",
      },
    ],
    isOpen: true,
    hours: "باز ۰۹:۰۰ · بسته ۱۷:۰۰",
    dailyTrend: [42, 44, 45, 43, 47, 48, 51, 49, 52, 56],
    weeklyTrend: [38, 40, 39, 42, 44, 43, 48, 46, 51, 54],
  },
  revenue: [
    { month: "بهمن", revenue: 1900, profit: 520 },
    { month: "اسفند", revenue: 2200, profit: 650 },
    { month: "فروردین", revenue: 2050, profit: 610 },
    { month: "اردیبهشت", revenue: 2750, profit: 760 },
    { month: "خرداد", revenue: 3150, profit: 820 },
    { month: "تیر", revenue: 3050, profit: 790 },
    { month: "مرداد", revenue: 3429, profit: 890 },
  ],
  categories: [
    { label: "انگشتر", value: 38 },
    { label: "گردنبند", value: 26 },
    { label: "دستبند", value: 18 },
    { label: "سفارشی", value: 10 },
  ],
  transactions: [
    {
      id: "VD-۲۰۲۶-۰۴۱۸",
      customer: "بهاره شریفی",
      detail: "۱۴:۵۲ · فاکتور پرداخت‌شده · VD-۲۰۲۶-۰۴۱۸",
      amount: "+$۱۴۸,۵۰۰",
      positive: true,
    },
    {
      id: "TF-۰۰۹۱",
      customer: "گروه کیان‌مهر",
      detail: "۱۳:۲۰ · سپرده امانی · TF-۰۰۹۱",
      amount: "+$۶۰,۰۰۰",
      positive: true,
    },
    {
      id: "INS-۰۴۴۲",
      customer: "امیر تهرانی",
      detail: "۱۲:۰۴ · قسط · INS-۰۴۴۲",
      amount: "+$۵,۲۰۰",
      positive: true,
    },
    {
      id: "PO-۳۳۱۲",
      customer: "آتلیه زرنگار",
      detail: "۱۱:۱۵ · پرداخت به تأمین‌کننده · PO-۳۳۱۲",
      amount: "−$۸۴,۰۰۰",
      positive: false,
    },
    {
      id: "VD-۲۰۲۶-۰۴۱۶",
      customer: "گروه کیان‌مهر",
      detail: "۱۰:۳۸ · فاکتور پرداخت‌شده · VD-۲۰۲۶-۰۴۱۶",
      amount: "+$۳۸۴,۰۰۰",
      positive: true,
    },
  ],
  upcomingPayments: [
    {
      id: "payment-1",
      title: "قسط · امیر تهرانی",
      dueDate: "سررسید ۱۸ مرداد",
      amount: "$۵,۲۰۰",
    },
    {
      id: "payment-2",
      title: "قسط وام · بانک پاسارگاد",
      dueDate: "سررسید ۲۱ مرداد",
      amount: "$۳۱,۴۰۰",
    },
    {
      id: "payment-3",
      title: "تأمین‌کننده · گوهر پارس",
      dueDate: "سررسید ۲۴ مرداد",
      amount: "$۴۶,۸۰۰",
    },
    {
      id: "payment-4",
      title: "ذخیره مالیاتی · فصل سوم",
      dueDate: "سررسید ۶ شهریور",
      amount: "$۱۱۸,۰۰۰",
    },
  ],
};
