import { CalendarDays } from "lucide-react";
import { useOperations } from "./features/operations/OperationsContext";
import { formatMoney } from "./lib/money";

export function BoltReportsPage(){
 const{data}=useOperations();const issued=data.invoices.filter(i=>i.status!=="Voided");const revenue=issued.reduce((s,i)=>s+i.grandTotalRials,0);const tax=issued.reduce((s,i)=>s+i.items.reduce((x,it)=>x+(it.taxRials||0),0),0);const receivable=data.orders.reduce((s,o)=>s+Math.max(0,o.grandTotalRials-data.payments.filter(p=>p.orderId===o.id&&p.status==="Verified").reduce((x,p)=>x+p.amountRials,0)),0);const avg=issued.length?revenue/issued.length:0;const bars=issued.slice(0,8);const max=Math.max(1,...bars.map(i=>i.grandTotalRials));
 return <main className="module-main bolt-page"><header className="page-header"><div><h1>Executive Store Analytics & Reports</h1><p>GST Tax Liabilities, custom date-range margins, and product sales insights</p></div><div className="receipt-actions"><button className="outline-action"><CalendarDays size={15}/> Custom Date Range</button><button className="outline-action">Last 30 Days</button></div></header><div className="header-divider"/>
 <div className="rates-bar"><span className="rates-label">LIVE INDEX RATES:</span>{data.marketPrices.slice(0,3).map(p=><span key={p.id}>{p.priceType}: <strong>{formatMoney(p.sellPriceRials)}/g</strong></span>)}</div>
 <div className="metrics-grid"><section className="metric-card panel"><span className="metric-label">GROSS METAL BILLING</span><strong>{formatMoney(revenue)}</strong><p className="green">● {issued.length} issued invoices</p></section><section className="metric-card panel"><span className="metric-label">ESTIMATED TAX / VAT</span><strong>{formatMoney(tax)}</strong><p className="gray">From invoice item tax records</p></section><section className="metric-card panel"><span className="metric-label">ACCOUNTS RECEIVABLE</span><strong>{formatMoney(receivable)}</strong><p className="orange">Open order balances</p></section><section className="metric-card panel"><span className="metric-label">AVG TRANSACTION SIZE</span><strong>{formatMoney(avg)}</strong><p className="green">Real invoice average</p></section></div>
 <div className="reports-layout"><div className="report-list"><span className="metric-label">SELECT REPORT PREVIEW</span>{[["Revenue & Metal Turn","Invoice value and metal weights"],["GST & Tax Compliance","Tax amounts recorded on invoices"],["Outstanding Dues History","Open customer balances"],["Customer Loyalty Log","Customer purchase history"]].map(([a,b],i)=><button className={`report-select ${i===0?"selected":""}`} key={a}><strong>{a}</strong><small>{b}</small><b>{i===0?"›":""}</b></button>)}</div>
 <section className="chart-card panel"><div className="chart-header"><div><h2>Active Preview: Revenue & Metal Turn</h2><p>Invoice totals from the live Vendome operational snapshot</p></div><button className="outline-action">CSV (Excel)</button></div><div className="bar-chart">{bars.map((i,n)=><div className="bar-column" key={i.id}><span>{formatMoney(i.grandTotalRials)}</span><div className={`bar ${n===bars.length-1?"highlighted":""}`} style={{height:`${Math.max(12,i.grandTotalRials/max*78)}%`}}/><small>{new Date(i.issuedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small></div>)}</div><div className="chart-footer"><span>TOTAL INVOICED<strong>{formatMoney(revenue)}</strong></span><span>TAX RECORDED<strong>{formatMoney(tax)}</strong></span><span>OPEN RECEIVABLE<strong>{formatMoney(receivable)}</strong></span></div></section></div></main>
}
