import { useState, type FormEvent } from "react";
import { useOperations } from "./features/operations/OperationsContext";
import type { StoreProfile } from "./features/operations/operations.types";
import { formatMoney } from "./lib/money";

export function BoltSettingsPage({onNotice}:{onNotice:(message:string)=>void}){
 const{data,request,refresh}=useOperations();const[saving,setSaving]=useState(false);const p=data.storeProfile;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await request<StoreProfile>("/api/v1/settings/store-profile",{method:"PUT",body:JSON.stringify({tradeName:String(f.get("tradeName")||"").trim(),legalName:String(f.get("legalName")||"").trim(),nationalId:String(f.get("nationalId")||"").trim()||null,economicCode:String(f.get("economicCode")||"").trim()||null,registrationNumber:String(f.get("registrationNumber")||"").trim()||null,phoneNumber:String(f.get("phoneNumber")||"").trim(),postalCode:String(f.get("postalCode")||"").trim(),addressLine:String(f.get("addressLine")||"").trim(),rowVersion:p?.rowVersion||null})});await refresh();onNotice("Store settings saved.");}catch(err){onNotice(err instanceof Error?err.message:"Settings could not be saved.");}finally{setSaving(false)}}
 return <main className="module-main bolt-page"><header className="page-header"><div><h1>Workspace settings</h1><p>GST rules, store layout setups, active team roles, and print triggers</p></div><button className="dark-action" onClick={()=>document.querySelector<HTMLFormElement>(".bolt-settings-form")?.requestSubmit()}>Save Settings Profile</button></header><div className="header-divider"/>
 <div className="rates-bar"><span className="rates-label">LIVE INDEX RATES:</span>{data.marketPrices.slice(0,3).map(x=><span key={x.id}>{x.priceType}: <strong>{formatMoney(x.sellPriceRials)}/g</strong></span>)}</div>
 <div className="settings-layout"><div><section className="settings-card panel"><h2>1. STORE PROFILE METADATA</h2><form className="settings-fields bolt-settings-form" onSubmit={submit}><label>Registered Name<input name="legalName" defaultValue={p?.legalName||p?.tradeName||""}/></label><label>GST / VAT Registration Number<input name="nationalId" defaultValue={p?.nationalId||""}/></label><label>Trade Name<input name="tradeName" defaultValue={p?.tradeName||""}/></label><label>Registration Number<input name="registrationNumber" defaultValue={p?.registrationNumber||""}/></label><label>Phone<input name="phoneNumber" defaultValue={p?.phoneNumber||""}/></label><label>Postal Code<input name="postalCode" defaultValue={p?.postalCode||""}/></label><label className="bolt-wide-field">Address<input name="addressLine" defaultValue={p?.addressLine||""}/></label><label className="bolt-wide-field">Economic Code<input name="economicCode" defaultValue={p?.economicCode||""}/></label><div className="form-actions"><button className="dark-action" type="submit" disabled={saving}>{saving?"Saving…":"Save Settings"}</button></div></form></section>
 <section className="settings-card panel"><h2>2. GLOBAL TAX & DUTY CALCULATION</h2><div className="advanced-box"><span>Live market prices are read from configured pricing endpoints.</span><span className="filter-chip active">Dynamic</span><span>Invoice tax values are read from real item tax records.</span><span className="filter-chip">API Driven</span></div></section>
 <section className="settings-card panel"><h2>3. STAFF TERMINAL ROLES & ALERTS</h2>{data.employees.slice(0,3).map(e=><div className="role-row" key={e.id}><strong>{e.displayName}<small>{e.roles.join(" · ")||"Employee"}</small></strong><span className="filter-chip">{e.isActive?"Active":"Inactive"}</span></div>)}</section></div>
 <section className="printer-card panel"><h2>Receipt Printer Template</h2><p>Adjust default parameters for fast thermal tape receipt generation.</p><div className="printer-preview"><strong>{p?.tradeName||"Vendome"} <span>LIVE</span></strong><hr/>Latest invoice values and print triggers are supplied by live operational data.<hr/><strong>GRAND TOTAL <span>{data.invoices[0]?formatMoney(data.invoices[0].grandTotalRials):"—"}</span></strong></div><span className="metric-label">ALERTS & NOTIFICATIONS</span><p className="switch-label"><i className="switch on"/> Desktop print integration</p></section></div></main>
}
