<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GoldInvoice.Worker-346f6b67-a22a-4377-b08a-707f2b97f247</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldInvoice.Application\GoldInvoice.Application.csproj" />
    <ProjectReference Include="..\GoldInvoice.Contracts\GoldInvoice.Contracts.csproj" />
    <ProjectReference Include="..\GoldInvoice.Infrastructure\GoldInvoice.Infrastructure.csproj" />
  </ItemGroup>
</Project>
